# Generated by Django 5.2.7 on 2025-10-18 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_course_subtopic_module_contentitem_topic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentitem',
            name='subtopic',
        ),
        migrations.AddField(
            model_name='contentitem',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='pages.topic'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of content within the topic.'),
        ),
        migrations.DeleteModel(
            name='SubTopic',
        ),
    ]
