# Generated by Django 5.2.7 on 2025-10-18 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_contentitem_subtopic_contentitem_topic_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentitem',
            options={'ordering': ['order'], 'verbose_name_plural': 'Content Items'},
        ),
    ]
